### ISSUE TITLE
Data type of value array returned by callbacks

### ISSUE THREAD

**Issue by kohr-h** [cicwi/tomopackets#1]
The `'uint32'` data type seems rather limiting and unnecessarily hard to handle, in particular what values should be mapped to 0 and max when converting from floating point. 

I suggest that we change the machinery to use `'float32'` values instead.

**Comment by jwbuurlage** [comment]
I always prefer using integer types over floating point types for communication, but the conversions may be a bit tedious.  I would not necessarily mind changing this to floats. I had the feeling that many real-world data sets are defined in terms in integral values but maybe this is not true.

**Comment by kohr-h** [comment]
> I always prefer using integer types over floating point types for communication, but the conversions may be a bit tedious.

Related to #2, if the platform makes a clear distinction between the visualization and control server and the clients that compute stuff, it makes sense to use the data type most appropriate for the server's task.
Then it would be good if the protocol would allow sending some meta-information about the data that gives the visualizer also more things to show and let the user manipulate the output (e.g. choose colormap based on density values, not gray values).

**Comment by jwbuurlage** [comment]
I have updated the system to use 32 bit floats, please update your program accordingly.
