### ISSUE TITLE
Responsibilities

### ISSUE THREAD

**Issue by kohr-h** [cicwi/TomoPackets#2]
This is more a question than a comment.

I suppose the client code that registers the slice callback with the server is responsible for all the details of the problem, i.e., define the geometry, the volume, etc.

Does it then make sense to say that currently, the client takes care of the physical world and works with sizes, distances, etc. in physical units, while the server just looks at raw data as volumes or images without any reference to the physical world?
If true, that also means that the visualizer has no access to this information, which could be very useful when looking at reconstructions (e.g. have colors mapped to density values, not unsigned ints). Likewise for the physical parameters of geometry, volume, detector etc.

I guess this turned into a feature request :-)

**Comment by jwbuurlage** [comment]
There is a `GeometrySpecificationPacket` which currently has the following fields:
```cpp
bool parallel;
int32_t projections;
std::array<float, 3> volume_min_point;
std::array<float, 3> volume_max_point;
```
But this can easily be extended. Maybe we need to have a discussion about what other stuff we want to put in there, and if this packet is the appropriate place for everything.

**Comment by kohr-h** [comment]
> But this can easily be extended. Maybe we need to have a discussion about what other stuff we want to put in there, and if this packet is the appropriate place for everything.

Yes, let's see what useful stuff we can put in there.
